### ISSUE TITLE
Home Assistant component?

### ISSUE THREAD

**Issue by adamderuwe** [dethpickle/python-opensprinkler#1]
Are you working on integrating your API w/ HA?  Just curious before I spend time figuring it out :)

**Comment by dethpickle** [comment]
Yup.  That was my sole purpose in working on this.  I have it working - so far as a platform for switch - at a very basic level here: https://github.com/dethpickle/home-assistant/tree/opensprinkler  That branch was current as of 0.47.  I've been out for a couple weeks.

config would look like this:
```yaml
switch:
    platform: opensprinkler
    host: !secret your_OpenSprinkler_FQDN_or_IP
    password: !secret your_OS_password_hash
    name: OpnSpr
    default_runtime: 64800
```
default_runtime is optional and would be, I think, 10 minutes normally (in seconds).  I'm using mine for controlling my pool, so I have it set to 18 hours because I'm really using them as switches.

So, a few things.  This is really basic right now.  Just switches.  On/Off.  You can give it a duration if you're calling it from script in HA, but the GUI is just a light switch.  

There is another guy doing a much more complete [python library](https://github.com/devanl/pyOpenSprinklerRest), which you've probably seen.  "Complete" on the details side - he doesn't have the actual station on/off controls, which is all I really need.  He's been sidetracked by new family demands.  He's got far more of the OS innards exposed in the library.  I've been focusing almost entirely just on getting the relays to fire at the expense of everything else (and it shows).  I'm also suffering from a lack of time - part of why I haven't posted anything.  I've also been away on work for a few weeks and had to walk away from this right after those last few commits.  But... as far as exposing the OS stations in HA, python-opensprinkler and the HA branch I have do work.  Almost nothing else from OS functionality does.  I'm a pretty miserable programmer.  I find it fun, but not always easy.  I'm just plugging away here because I'm amazed that more doesn't exist already.  Feel free to use what you want and jump ahead or build a new one.  I'll come back on to this soon, I hope.

I think my biggest blindspot for any of this is going to be that I only have an OS 3.0 and the latest firmware.  Older stuff may or may not work at all.

Cheers.

**Comment by adamderuwe** [comment]
Glad to hear it.  I like where you're going!  I was originally following devanl's work,, but wasn't a huge fan.  I like your library much better.

I updated to 2.1.7 firmware a week or so ago after seeing your library is built for that.  I am running [this](http://www.diygadget.com/tiao-smart-network-sprinkler-controller-16-station-sprinkler-controller-open-source-desktop-mobile-app.html) hardware, which from the software perspective, is OpenSprinkler.

I'd love to see information about last run time and next run time in HA.  Maybe I'll look into it.  I'm a C# developer and haven't taken much time to master Python yet.

**Comment by nalipaz** [comment]
So if we want to try out your component do we just need to drop in the https://github.com/dethpickle/home-assistant/blob/opensprinkler/homeassistant/components/switch/opensprinkler.py file? I think that would go under `~/.home-assistant/custom_components/switch/` or are you only forking home-assistant's project?

**Comment by dethpickle** [comment]
Just forking.  I'd not run off of my repo as it could very well be behind.  If you place it in your own `homeassistant/components/switch/` off of the real repo, it should work.  Keep in mind that the only functionality I have right now is switching elements on and off, which does work.  I apologize I haven't had the time to work on it lately.  Seeing that things like RainMachine have good integrations with HA, I might try to model after them (or you can).  

Do know that my intentions for using OpenSprinkler have always been as it being just a relay with a brain.  I'm not using it for actual sprinklers.  My intended use as for controlling my pool equipment.  It has the benefit over my current system of being wireless and I can get rid of some unsightly cables running all over my garage and the outside of the house.

**Comment by nalipaz** [comment]
From my understanding the custom components of this sort typically work when placed under `~/.home-assistant/custom_components/`. I did that that for my garage when `myq` was not yet a core component and it worked great without the need to alter the core install in any way. I will try with yours once I get my opensprinkler, currently just been researching the idea of using it.

**Comment by adamderuwe** [comment]
While waiting on this component, I've used rest binary sensors.
```

binary_sensor:
 - platform: rest
   name: "Back Yard 1"
   resource: http://sprinkler.abl/js?pw=aa
   value_template: '{{value_json.sn[0]}}'
 - platform: rest
   name: "Back Yard 2"
   resource: http://sprinkler.abl/js?pw=aa
   value_template: '{{value_json.sn[1]}}'
 - platform: rest
   name: "Back Yard 3"
   resource: http://sprinkler.abl/js?pw=aa
   value_template: '{{value_json.sn[2]}}'
 - platform: rest
   name: "Front Yard 1"
   resource: http://sprinkler.abl/js?pw=aa
   value_template: '{{value_json.sn[3]}}'
 - platform: rest
   name: "Front Yard 2"
   resource: http://sprinkler.abl/js?pw=aa
   value_template: '{{value_json.sn[4]}}'
sensor:
 - platform: rest
   name: Sprinklers Last Run
   resource: http://sprinkler.abl/jc?pw=aa
   value_template: '{{value_json.lrun[3] | timestamp_utc }}'
```

It looks like this:
![image](https://user-images.githubusercontent.com/17112032/30608178-62188188-9d2c-11e7-9c7e-d91bd56e445d.png)
